### ISSUE TITLE
请问现在还能用吗？

### ISSUE THREAD

**Issue by fatfish516** [IanSmith123/Wox.Plugin.iciba#1]
刚刚下载了之后发现不能使用了

**Comment by IanSmith123** [comment]
![image](https://user-images.githubusercontent.com/19611084/44982991-2e3f4680-afaa-11e8-8a07-67b8c4aa36a1.png)
还可以使用

PS:有道翻译比我写的这个插件好用，我已经停止维护该仓库了 :)
使用方法见  http://www.wox.one/plugin/78

**Comment by IanSmith123** [comment]
刚刚测试了下，可能存在的问题：
1. 使用了python调用爱词霸词典的api，请检查电脑中是否安装python并且添加python到环境变量
2. 程序使用了requests来请求api, 请检查是否安装了requests
3. 插件使用的python 3.6才支持的fstring, 请检查python版本是否高于（包括）python3.6
